[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
serviceName = "discord-key-manager"

[services.source]
repo = "."

[services.variables]
NODE_ENV = "production"
PORT = "3000"